# context_manager.py
# date created: 2026-02-12 19:08:42
# date modified: 2026-05-25 19:50:51
# tags: #context, #entities, #facts, #lifecycle, #updates

"""
context_manager.py — Context Category management for Evelyn's memory system.

Provides two sets of functionality:
  - Standalone helper functions used by ``evelyn_tools.py`` and other modules:
      append_context_log()  — Create a new context fact file.
      search_vault_map()    — Keyword search across the full vault map JSON.
  - These same functions are registered as LLM-callable tools in ``evelyn_tools.py``.

Context entries are written to ``PENDING_DIR`` which lives inside the main
vault directory tree (visible to gist/sync pipeline) while remaining in a
reviewable ``Pending`` subfolder.

Key path constants:
  CONTEXT_DIR    — Live context category markdown files in the Obsidian Vault.
  vault_db       — SQLite index of the entire vault, generated by vault_indexer.py.
  PENDING_DIR    — In-vault staging folder for new context entries.
"""

import os
import re
import datetime
import evelyn_config as cfg
import json

def append_context_log(
    category_code: str,
    summary: str,
):
    """
    Creates a new Context Entry in the SQLite memory DB, pending review.

    Args:
        category_code: Primary category identifier, e.g. ``"Cat08-R"`` or ``"Cat01-E"``.
        summary: The fact or event to log. Should be a concise, self-contained statement.

    Returns:
        str: A human-readable confirmation message with the ID that was created.
    """
    import memory_db
    
    today = datetime.date.today().strftime("%Y-%m-%d")
    
    # Determine subject from category code suffix
    subject_code = category_code[-1].upper() if category_code else ""
    subject = cfg.ASSISTANT_NAME if subject_code == cfg.SUBJECT_CODE_ASSISTANT else (cfg.USER_NAME if subject_code == cfg.SUBJECT_CODE_USER else "Unknown")

    try:
        row_id = memory_db.insert_entry(
            category=category_code,
            subject=subject,
            observation=summary,
            confidence="medium",
            source="manual",
            status="pending_review",
            date=today
        )
    except Exception as e:
        return f"Error writing context entry: {e}"

    return f"Created Context Entry (ID: {row_id}) pending review."


def search_vault_map(query: str, limit: int = 5) -> str:
    """Searches the SQLite vault map for files matching the query string.

    Scoring heuristic (higher = stronger match):
      +10 points  -- query found in the file title
      +5 points   -- query found in a tag
      +2 points   -- query found in the text preview snippet

    Results are sorted by descending score; only the top ``limit`` entries
    are returned. Matching is case-insensitive.

    Args:
        query: The search term (e.g. ``"Tenser"`` or ``"Void Connections"``).
        limit: Maximum number of results to return. Defaults to 5.

    Returns:
        str: A formatted, human-readable block of the top matches, each showing
        title, file path, tags, and snippet. Returns an error string if the vault
        map database is missing or unreadable.
    """
    import vault_db
    
    try:
        results = vault_db.search_documents(query, limit=limit)
    except Exception as e:
        return f"Error reading vault map database: {e}"

    if not results:
        return f"No results found in the Obsidian Vault for '{query}'."

    output = f"Top {len(results)} Vault Search Results for '{query}':\n\n"
    for r in results:
        output += f"--- {r['title']} ---\n"
        output += f"Path: {r['path']}\n"
        if r["tags"]:
            output += f"Tags: {', '.join(r['tags'])}\n"
        snippet = r.get("snippet") or r.get("gist") or ""
        output += f"Preview: {snippet}\n\n"

    return output.strip()


def update_context_log(target_filepaths: list, new_summary: str) -> str:
    """
    Creates an update proposal for existing context entries.

    Args:
        target_filepaths: List of target paths or IDs (currently passed as paths by LLM).
        new_summary: The new fact/summary data.

    Returns:
        str: Confirmation message.
    """
    import memory_db
    
    source_ids = []
    for p in target_filepaths:
        # Extract ID if RAG source format is passed
        if isinstance(p, str) and p.startswith("sqlite::context_entry::"):
            p = p.split("::")[-1]
            
        try:
            target_id = int(p)
        except ValueError:
            continue
            
        con = memory_db.get_db()
        row = con.execute("SELECT id FROM context_entries WHERE id = ?", (target_id,)).fetchone()
        con.close()
        if row:
            source_ids.append(row["id"])
            
    try:
        pid = memory_db.insert_proposal(
            type="update_request",
            source_ids=source_ids,
            reason=f"update requested by {cfg.ASSISTANT_NAME}",
            merged_observation=new_summary,
            status="pending"
        )
    except Exception as e:
        return f"Error creating update proposal: {e}"

    return f"Update proposal created (ID: {pid}) for {cfg.USER_NAME} to review."
