"""
context_manager.py — Context Category management for Evelyn's memory system.

Provides two sets of functionality:
  - Standalone helper functions used by ``evelyn_tools.py`` and other modules:
      append_context_log()  — Create a new context fact file.
      search_vault_map()    — Keyword search across the full vault map JSON.
  - These same functions are registered as LLM-callable tools in ``evelyn_tools.py``.

Context entries are written to ``PENDING_DIR`` which lives inside the main
vault directory tree (visible to gist/sync pipeline) while remaining in a
reviewable ``Pending`` subfolder.

Key path constants:
  CONTEXT_DIR    — Live context category markdown files in the Obsidian Vault.
  VAULT_MAP_FILE — JSON index of the entire vault, generated by generate_vault_map.py.
  PENDING_DIR    — In-vault staging folder for new context entries.
"""

# context_manager.py

import os
import datetime
import json

import evelyn_config as cfg # [[evelyn_config.py]]

CONTEXT_DIR = r"G:\My Drive\Obsidian_Vault\Evelyn\Evelyn's Context\Context Categories"
VAULT_MAP_FILE = r"C:\Projects\LocalAI\Vault_Map\vault_map_data.json" # [[vault_map_data.json]]

# These are sourced from evelyn_config so paths stay in one place.
PENDING_DIR = cfg.PENDING_DIR


def append_context_log(
    category_code: str,
    summary: str,
    secondary_cats: list = None,
):
    """
    Creates a new Context Entry markdown file in the in-vault Pending folder.

    The file is written to the vault's ``Pending`` subfolder for review.
    It is visible to the gist/sync pipeline immediately.

    Filename format: ``CE_<YYYY-MM-DD>_<category_code>.md``
    If a file with the same name already exists for today, a numeric suffix is
    appended (e.g. ``CE_2026-03-17_Cat01 (1).md``) to avoid collisions.

    Args:
        category_code: Primary category identifier, e.g. ``"Cat08-R"`` or ``"Cat01-E"``.
        summary: The fact or event to log. Should be a concise, self-contained statement.
        secondary_cats: Optional list of additional category codes to cross-reference
            (e.g. ``["Cat02-E", "Cat05-R"]``). Rendered as Obsidian wiki-links.

    Returns:
        str: A human-readable confirmation message with the filename that was created.
    """
    if not os.path.exists(PENDING_DIR):
        os.makedirs(PENDING_DIR, exist_ok=True)

    # 2. Format File Name and Content
    today = datetime.date.today().strftime("%Y-%m-%d")
    filename = f"CE_{today}_{category_code}.md"

    # Handle multiple entries on the same day gracefully
    counter = 1
    filepath = os.path.join(PENDING_DIR, filename)
    while os.path.exists(filepath):
        filename = f"CE_{today}_{category_code} ({counter}).md"
        filepath = os.path.join(PENDING_DIR, filename)
        counter += 1

    primary_tag = category_code
    secs = ", ".join(secondary_cats) if secondary_cats else ""
    secondary_line = f"**Secondary:** {secs}\n\n" if secs else ""

    file_content = f"""---
tags: [CY-{today.replace("-", "/")}]
---

# {filename.replace(".md", "")}

**Primary:** {primary_tag}

{secondary_line}**Summary:** {summary}
"""

    # 3. Create File
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(file_content)
    except OSError as e:
        return f"Error writing context entry — is Google Drive available? Details: {e}"

    return f"Created Context Entry: {filename} in Pending folder."


def search_vault_map(query: str, limit: int = 5) -> str:
    """
    Searches the JSON vault map for files matching the query string.

    Scoring heuristic (higher = stronger match):
      +10 points  -- query found in the file title
      +5 points   -- query found in a tag
      +2 points   -- query found in the LLM-generated gist

    Results are sorted by descending score; only the top ``limit`` entries
    are returned. Matching is case-insensitive.

    Args:
        query: The search term (e.g. ``"Tenser"`` or ``"Void Connections"``).
        limit: Maximum number of results to return. Defaults to 5.

    Returns:
        str: A formatted, human-readable block of the top matches, each showing
        title, file path, tags, and gist. Returns an error string if the vault
        map file is missing or unreadable.
    """
    if not os.path.exists(VAULT_MAP_FILE):
        return "Error: Vault map file not found."

    try:
        with open(VAULT_MAP_FILE, "r", encoding="utf-8") as f:
            vault_data = json.load(f)
    except Exception as e:
        return f"Error reading vault map: {e}"

    query_lower = query.lower()
    results = []

    for rel_path, file_info in vault_data.items():
        data = file_info.get("data", {})
        if not data:
            continue

        title = data.get("title", "").lower()
        tags = [t.lower() for t in data.get("tags", [])]
        gist = data.get("gist", "").lower()

        score = 0
        if query_lower in title:
            score += 10
        if any(query_lower in t for t in tags):
            score += 5
        if query_lower in gist:
            score += 2

        if score > 0:
            results.append(
                {
                    "path": rel_path,
                    "title": data.get("title", ""),
                    "score": score,
                    "tags": data.get("tags", []),
                    "gist": data.get("gist", ""),
                }
            )

    if not results:
        return f"No results found in the Obsidian Vault for '{query}'."

    results.sort(key=lambda x: x["score"], reverse=True)

    output = f"Top {min(limit, len(results))} Vault Search Results for '{query}':\n\n"
    for r in results[:limit]:
        output += f"--- {r['title']} ---\n"
        output += f"Path: {r['path']}\n"
        if r["tags"]:
            output += f"Tags: {', '.join(r['tags'])}\n"
        output += f"Gist: {r['gist']}\n\n"

    return output.strip()


def update_context_log(target_filepaths: list, new_summary: str) -> str:
    """
    Creates an update request file for one or more existing Context Fact files.

    The file is placed in PENDING_DIR for Ricky to review — it is NOT applied
    directly to the vault.

    Args:
        target_filepaths: List of absolute or vault-relative paths to update.
        new_summary: The new fact/summary data to insert into those files.

    Returns:
        str: Confirmation message with the filename created, or an error string.
    """
    if not os.path.exists(PENDING_DIR):
        os.makedirs(PENDING_DIR, exist_ok=True)

    today = datetime.date.today().strftime("%Y-%m-%d")
    timestamp = datetime.datetime.now().strftime("%H%M%S")
    filename = f"[UPDATE_REQUEST]_{today}_{timestamp}.md"
    filepath = os.path.join(PENDING_DIR, filename)

    paths_str = "\n".join([f"- {p}" for p in target_filepaths])

    file_content = f"""# Update Request

Please update the following context files:
{paths_str}

## New Summary Data:
{new_summary}
"""
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(file_content)
    except OSError as e:
        return f"Error writing update request — is Google Drive available? Details: {e}"

    return f"Update request created for Ricky to review: {filename} created in Pending Approvals Folder."
