# ingest_gists.py
# date created: 2026-05-03 18:05:36
# date modified: 2026-05-25 19:50:51
# tags: #gists, #ingest, #indexing, #memory, #pipeline

"""
ingest_gists.py — Syncs Obsidian Vault gists into Chroma.

Reads the vault map generated by vault_indexer.py and uploads
LLM-generated gist summaries into the Chroma 'evelyn_gists' collection.

Key behaviour:
  - State file (gist_sync_state.json) stores mtime per source file.
  - Only changed gists are re-ingested on subsequent runs.
  - GC removes Chroma records for files removed from the vault map.
  - Excludes Evelyn's own directory (handled by ingest_obsidian_knowledge.py).

Run directly or imported via sync_context_memory() in evelyn_tools.py.
"""

import os
import sys
import json
import time

# Chroma RAG wrapper
ROOT_DIR  = r"C:\Projects\LocalAI"
TOOLS_DIR = r"C:\Projects\LocalAI\Evelyn\tools"
for _d in (ROOT_DIR, TOOLS_DIR):
    if _d not in sys.path:
        sys.path.insert(0, _d)
import chroma_rag  # noqa: E402

# Paths
SYNC_STATE_FILE = r"C:\Projects\LocalAI\data\gist_sync_state.json" # [[gist_sync_state.json]]
COLLECTION_NAME = "evelyn_gists"

# Excluded paths — handled by [[ingest_obsidian_knowledge.py]]
EVELYN_DIR         = r"G:\My Drive\Obsidian_Vault\Evelyn"
PHYSICAL_DESC_FILE = r"G:\My Drive\Obsidian_Vault\Notes\Prompt Lab\Physical Descriptions\Physical Description - Evelyn.md" # [[Physical Description - Evelyn.md]]


# ---------------------------------------------------------------------------
# State helpers
# ---------------------------------------------------------------------------

def load_state(state_file):
    """Load sync state, auto-migrating old {path: float} format."""
    if not os.path.exists(state_file):
        return {}
    try:
        with open(state_file, "r", encoding="utf-8") as f:
            raw = json.load(f)
        state = {}
        for k, v in raw.items():
            if isinstance(v, (int, float)):
                state[k] = {"mtime": float(v)}
            elif isinstance(v, dict):
                state[k] = v
        return state
    except Exception:
        print("Could not read state file, starting fresh.")
        return {}


def save_state(state, state_file):
    """Persist state to disk."""
    with open(state_file, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=4)


def format_gist_document(file_path, gist_text, tags, title=None):
    """Format a gist into a plain-text document for Chroma storage."""
    safe_title = title if title else os.path.basename(file_path).replace(".md", "")
    parts = [f"Topic: {safe_title}", f"File Path: {file_path}"]
    if tags:
        parts.append(f"Tags: {', '.join(tags)}")
    parts.append("")
    parts.append(gist_text)
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Main sync
# ---------------------------------------------------------------------------

def main():
    """
    Full incremental sync of vault gists into Chroma.

    Pipeline:
      1. Load all documents from evelyn_vault.db.
      2. Load state from gist_sync_state.json.
      3. GC: remove Chroma records for files no longer in the vault map.
      4. For each vault file with a gist (non-excluded, mtime changed):
           upsert into Chroma.
      5. Save final state to disk.
    """
    import vault_db
    try:
        documents = vault_db.get_all_documents()
    except Exception as e:
        print(f"Error reading vault DB: {e}")
        return

    state = load_state(SYNC_STATE_FILE)

    # Build active gistable paths (non-excluded, has gist content)
    active_paths = set()
    vault_data = {}
    for doc in documents:
        file_path = doc["path"]
        vault_data[file_path] = doc
        if file_path.startswith(EVELYN_DIR) or file_path == PHYSICAL_DESC_FILE:
            continue
        if doc.get("gist"):
            active_paths.add(file_path)

    processed = skipped = cleaned = 0

    # Garbage collection
    for stale_path in list(state.keys()):
        if stale_path not in active_paths:
            print(f"GC: {os.path.basename(stale_path)}")
            chroma_rag.delete_document(stale_path, COLLECTION_NAME)
            del state[stale_path]
            cleaned += 1

    print("Starting gist sync...")

    for file_path in active_paths:
        doc = vault_data[file_path]
        mtime = doc.get("mtime", 0)
        gist = doc.get("gist", "")

        entry = state.get(file_path, {})
        stored_mtime = entry.get("mtime", 0) if isinstance(entry, dict) else float(entry)

        if stored_mtime >= mtime:
            skipped += 1
            continue

        document = format_gist_document(
            file_path, gist,
            [t.strip() for t in doc.get("tags", "").split(",") if t.strip()],
            title=doc.get("title"),
        )

        print(f"Ingesting gist: {os.path.basename(file_path)}")
        extra = {
            "title":        doc.get("title", ""),
            "tags":         doc.get("tags", ""),
            "rag_priority": doc.get("rag_priority", "normal"),
            "rag_pinned":   bool(doc.get("rag_pinned", False)),
            "aliases":      doc.get("aliases", ""),
            "gist":         gist,
        }
        if chroma_rag.ingest_markdown_file(file_path, document, COLLECTION_NAME, extra_metadata=extra):
            state[file_path] = {"mtime": mtime}
            processed += 1
        else:
            print(f"Ingest failed for {os.path.basename(file_path)}")

        # Checkpoint every 50 files
        if (processed + skipped) % 50 == 0:
            save_state(state, SYNC_STATE_FILE)

        time.sleep(0.05)

    save_state(state, SYNC_STATE_FILE)
    print(f"Gist sync complete. Processed: {processed}, Skipped: {skipped}, GC'd: {cleaned}")


if __name__ == "__main__":
    main()
