"""
ingest_gists.py — Syncs Obsidian Vault gists into Open WebUI's knowledge collection.

Reads the vault map generated by ``generate_vault_map.py`` and uploads
LLM-generated gist summaries (plus tags/links) into the "Evelyn Vault Gists"
knowledge collection in Open WebUI.

Key behaviour:
  - State file (``gist_sync_state.json``) stores mtime + Open WebUI file ID per
    source file. This allows updates to reliably delete the old record before
    re-uploading — no API file-listing lookup required.
  - State format: ``{source_path: {"mtime": float, "file_id": str|None}}``
    Old format (``{source_path: float}``) is automatically migrated on load.
  - Garbage collection: state entries for files removed from the vault map or
    belonging to excluded paths are cleaned up and their Open WebUI records removed.
  - Uses a path-derived ``safe_name`` (with ``.gist`` suffix) for uniqueness
    within Open WebUI's file storage.
  - Excludes Evelyn's own directory and physical description file (handled by
    ``ingest_obsidian_knowledge.py``).

Run directly (``python ingest_gists.py``) or imported and called via ``main()``
from ``openwebui_sync_tool.py``.
"""

import os
import json
import requests
import time

API_BASE = "http://localhost:8080/api/v1"
API_KEY = os.environ.get("OpenWebUI_API", "sk-768aef85b01e44349aae5a536cc47c10")
VAULT_MAP_FILE = r"c:\Projects\LocalAI\Vault_Map\vault_map_data.json"
SYNC_STATE_FILE = r"C:\Projects\LocalAI\Evelyn\tools\gist_sync_state.json"
KNOWLEDGE_NAME = "Evelyn Vault Gists"

# Excluded paths — handled by ingest_obsidian_knowledge.py
EVELYN_DIR = r"G:\My Drive\Obsidian_Vault\Evelyn"
PHYSICAL_DESC_FILE = r"G:\My Drive\Obsidian_Vault\Notes\Prompt Lab\Physical Descriptions\Physical Description - Evelyn.md"

headers = {"Authorization": f"Bearer {API_KEY}"}


# ---------------------------------------------------------------------------
# State helpers
# ---------------------------------------------------------------------------

def load_state(state_file):
    """
    Loads the sync state, migrating old format automatically.

    Old format: ``{source_path: mtime_float}``
    New format: ``{source_path: {"mtime": float, "file_id": str|None}}``

    Returns:
        dict: State dictionary in new format.
    """
    if not os.path.exists(state_file):
        return {}
    try:
        with open(state_file, "r", encoding="utf-8") as f:
            raw = json.load(f)
        state = {}
        for k, v in raw.items():
            if isinstance(v, (int, float)):
                state[k] = {"mtime": float(v), "file_id": None}
            elif isinstance(v, dict):
                state[k] = v
        return state
    except Exception:
        print("Could not read state file, starting fresh.")
        return {}


def save_state(state, state_file):
    """Persists state to disk."""
    with open(state_file, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=4)


def make_safe_name(file_path):
    """
    Derives a unique, filesystem-safe gist filename from a source file path.

    Replaces drive colons, backslashes, forward slashes, and spaces with
    underscores, then appends ``.gist`` so it is distinguishable from raw
    markdown uploads in Open WebUI's file storage.
    """
    return (
        file_path.replace(":", "")
                 .replace("\\", "_")
                 .replace("/", "_")
                 .replace(" ", "_")
        + ".gist"
    )


# ---------------------------------------------------------------------------
# Open WebUI API helpers
# ---------------------------------------------------------------------------

def get_or_create_knowledge():
    """
    Retrieves the ID for the ``"Evelyn Vault Gists"`` collection, creating it
    if it does not already exist.

    Returns:
        str: The UUID of the knowledge collection, or ``None`` on failure.
    """
    print(f"Checking for Knowledge Collection '{KNOWLEDGE_NAME}'...")
    response = requests.get(f"{API_BASE}/knowledge/", headers=headers)
    if response.ok:
        collections = response.json()
        if isinstance(collections, dict):
            collections = collections.get("items", [])
        for col in collections:
            if col.get("name") == KNOWLEDGE_NAME:
                print("Found existing collection.")
                return col["id"]

    print("Creating new Knowledge Collection.")
    payload = {
        "name": KNOWLEDGE_NAME,
        "description": "Auto-synced gists from Obsidian vault for Evelyn's Intuition RAG.",
    }
    resp = requests.post(f"{API_BASE}/knowledge/create", json=payload, headers=headers)
    if resp.ok:
        return resp.json()["id"]
    else:
        print(f"Failed to create collection: {resp.text}")
        return None


def remove_file_from_knowledge(collection_id, file_id):
    """Removes a specific file from the knowledge collection."""
    payload = {"file_id": file_id}
    requests.post(
        f"{API_BASE}/knowledge/{collection_id}/file/remove", json=payload, headers=headers
    )


def delete_file(file_id):
    """Deletes a file record from Open WebUI storage."""
    resp = requests.delete(f"{API_BASE}/files/{file_id}", headers=headers)
    if not resp.ok:
        print(f"Failed to delete file record {file_id}: {resp.text}")


def upload_gist_file(file_path, gist_text, tags, links, title=None, safe_name=None):
    """
    Uploads a formatted gist to Open WebUI file storage.

    Composes a plain-text document that combines the file path, title, tags,
    entity links, and the LLM-generated gist text into a single uploadable file.

    Args:
        file_path: Relative or absolute path to the source markdown file.
        gist_text: The LLM-generated summary/gist content.
        tags: List of tags associated with the file.
        links: List of wiki-links/entities found in the file.
        title: Optional display title. Defaults to the filename stem.
        safe_name: Unique filename to use in Open WebUI. Generated via
            ``make_safe_name`` if not provided.

    Returns:
        str: The Open WebUI file UUID on success, or ``None`` on failure.
    """
    safe_title = title if title else os.path.basename(file_path).replace(".md", "")
    content = f"Topic: {safe_title}\nFile Path: {file_path}\n"
    if tags:
        content += f"Tags: {', '.join(tags)}\n"
    if links:
        content += f"Entities: {', '.join(links)}\n"
    content += f"\n{gist_text}"

    if not safe_name:
        safe_name = make_safe_name(file_path)

    files = {"file": (safe_name, content.encode("utf-8"), "text/plain")}
    resp = requests.post(f"{API_BASE}/files/", files=files, headers=headers)
    if resp.ok:
        return resp.json()["id"]
    else:
        print(f"Failed to upload {safe_name}: {resp.text}")
        return None


def add_file_to_knowledge(collection_id, file_id):
    """
    Registers an already-uploaded gist file with the knowledge collection.

    Args:
        collection_id: UUID of the ``"Evelyn Vault Gists"`` collection.
        file_id: UUID of the uploaded file in Open WebUI's file storage.
    """
    payload = {"file_id": file_id}
    resp = requests.post(
        f"{API_BASE}/knowledge/{collection_id}/file/add", json=payload, headers=headers
    )
    if not resp.ok:
        print(f"Failed to add file {file_id} to collection {collection_id}: {resp.text}")


# ---------------------------------------------------------------------------
# Main sync
# ---------------------------------------------------------------------------

def main():
    """
    Entry point: runs the full incremental sync of vault gists into Open WebUI.

    Pipeline:
      1. Load ``vault_map_data.json`` (generated by ``generate_vault_map.py``).
      2. Load state from ``gist_sync_state.json`` (auto-migrates old format).
      3. Get or create the ``"Evelyn Vault Gists"`` knowledge collection.
      4. Garbage-collect: remove state entries (and their Open WebUI records)
         for files not present in the current vault map or belonging to excluded
         paths (Evelyn's own memory, handled by ``ingest_obsidian_knowledge.py``).
      5. For each vault file with a gist:
           - Skip Evelyn's directory and physical description file.
           - Skip if mtime unchanged (trust state).
           - If mtime changed and state has a file_id: delete old record first.
           - Upload new gist, register with collection, save new file_id to state.
           - Checkpoint state to disk every 50 files.
      6. Save final state to disk.
    """
    if not os.path.exists(VAULT_MAP_FILE):
        print(f"Vault map file not found: {VAULT_MAP_FILE}")
        return

    with open(VAULT_MAP_FILE, "r", encoding="utf-8") as f:
        vault_data = json.load(f)

    state = load_state(SYNC_STATE_FILE)

    collection_id = get_or_create_knowledge()
    if not collection_id:
        print("Cannot proceed without a target Knowledge Collection.")
        return

    # Build set of active paths (gistable, non-excluded)
    active_paths = set()
    for file_path, file_info in vault_data.items():
        if file_path.startswith(EVELYN_DIR) or file_path == PHYSICAL_DESC_FILE:
            continue
        if file_info.get("data", {}).get("gist", ""):
            active_paths.add(file_path)

    processed = 0
    skipped = 0
    cleaned = 0

    # Garbage collection: remove state entries for files no longer active
    for stale_path in list(state.keys()):
        if stale_path not in active_paths:
            entry = state[stale_path]
            file_id = entry.get("file_id") if isinstance(entry, dict) else None
            if file_id:
                print(f"GC: Removing obsolete gist: {os.path.basename(stale_path)}")
                remove_file_from_knowledge(collection_id, file_id)
                delete_file(file_id)
            del state[stale_path]
            cleaned += 1

    print("Starting gist sync...")

    for file_path in active_paths:
        file_info = vault_data[file_path]
        mtime = file_info.get("mtime", 0)
        data = file_info.get("data", {})
        gist = data.get("gist", "")

        entry = state.get(file_path, {})
        stored_mtime = entry.get("mtime", 0) if isinstance(entry, dict) else float(entry)

        # Skip if unchanged
        if stored_mtime >= mtime:
            skipped += 1
            continue

        safe_name = make_safe_name(file_path)

        # Delete old record if we have its ID
        old_file_id = entry.get("file_id") if isinstance(entry, dict) else None
        if old_file_id:
            print(f"Update detected: {os.path.basename(file_path)} — removing old gist.")
            remove_file_from_knowledge(collection_id, old_file_id)
            delete_file(old_file_id)

        # Upload new gist
        print(f"Uploading gist for: {os.path.basename(file_path)}")
        file_id = upload_gist_file(
            file_path,
            gist,
            data.get("tags", []),
            data.get("links", []),
            title=data.get("title"),
            safe_name=safe_name,
        )

        if file_id:
            add_file_to_knowledge(collection_id, file_id)
            state[file_path] = {"mtime": mtime, "file_id": file_id}
            processed += 1
        else:
            print(f"Upload failed for {os.path.basename(file_path)} — marking as synced.")
            state[file_path] = {"mtime": mtime, "file_id": old_file_id}

        # Checkpoint every 50 files
        if (processed + skipped) % 50 == 0:
            save_state(state, SYNC_STATE_FILE)

        time.sleep(0.1)

    save_state(state, SYNC_STATE_FILE)
    print(f"Gist sync complete. Processed: {processed}, Skipped: {skipped}, GC'd: {cleaned}")


if __name__ == "__main__":
    main()
