"""Module to ingest Obsidian gists into Open WebUI Knowledge collections.

Processes the vault map generated by `generate_vault_map.py` and uploads
new or modified gists to the RAG system for Evelyn's Intuition.
"""

import os
import json
import requests
import time

API_BASE = "http://localhost:8080/api/v1"
API_KEY = os.environ.get("OpenWebUI_API", "sk-768aef85b01e44349aae5a536cc47c10")
VAULT_MAP_FILE = r"c:\Projects\LocalAI\Vault_Map\vault_map_data.json"
SYNC_STATE_FILE = r"C:\Projects\LocalAI\Evelyn\tools\gist_sync_state.json"
KNOWLEDGE_NAME = "Evelyn Vault Gists"

# Excluded Paths (Handled by ingest_obsidian_knowledge.py)
EVELYN_DIR = r"G:\My Drive\Obsidian_Vault\Evelyn"
PHYSICAL_DESC_FILE = r"G:\My Drive\Obsidian_Vault\Notes\Prompt Lab\Physical Descriptions\Physical Description - Evelyn.md"

headers = {"Authorization": f"Bearer {API_KEY}"}


def get_or_create_knowledge():
    """Retrieves the ID for the 'Evelyn Vault Gists' collection or creates it.

    Returns:
        str: The UUID of the knowledge collection, or None if it fails.
    """
    print(f"Checking for Knowledge Collection '{KNOWLEDGE_NAME}'...")
    response = requests.get(f"{API_BASE}/knowledge/", headers=headers)
    if response.ok:
        collections = response.json().get("items", [])
        for col in collections:
            if col.get("name") == KNOWLEDGE_NAME:
                print("Found existing collection.")
                return col["id"]

    print("Creating new Knowledge Collection.")
    payload = {
        "name": KNOWLEDGE_NAME,
        "description": "Auto-synced gists from Obsidian vault for Evelyn's Intuition RAG.",
    }
    resp = requests.post(f"{API_BASE}/knowledge/create", json=payload, headers=headers)
    if resp.ok:
        return resp.json()["id"]
    else:
        print(f"Failed to create collection: {resp.text}")
        return None


def upload_gist_file(file_path, gist_text, tags, links, title=None):
    """Uploads a formatted gist to the OpenWebUI file storage.

    Args:
        file_path: Absolute path to the source markdown file.
        gist_text: The LLM-generated summary/gist content.
        tags: List of tags associated with the file.
        links: List of wiki-links/entities found in the file.
        title: Optional custom title. Defaults to filename if not provided.

    Returns:
        str: The generated OpenWebUI file ID on success, None on failure.
    """
    # We embed the file path so the LLM knows what to pass to the deep recall tool.
    # We use a fallback title just in case one isn't passed (though we'd need to update the caller too)
    safe_title = title if title else os.path.basename(file_path).replace(".md", "")
    content = f"Topic: {safe_title}\nFile Path: {file_path}\n"
    if tags:
        content += f"Tags: {', '.join(tags)}\n"
    if links:
        content += f"Entities: {', '.join(links)}\n"
    content += f"\n{gist_text}"

    # OpenWebUI requires multipart/form-data for file upload
    # We mock a file using a tuple
    safe_name = os.path.basename(file_path).replace(".md", "") + "_gist.txt"
    files = {"file": (safe_name, content.encode("utf-8"), "text/plain")}

    resp = requests.post(f"{API_BASE}/files/", files=files, headers=headers)
    if resp.ok:
        return resp.json()["id"]
    else:
        print(f"Failed to upload {safe_name}: {resp.text}")
        return None


def add_file_to_knowledge(collection_id, file_id):
    payload = {"file_id": file_id}
    resp = requests.post(
        f"{API_BASE}/knowledge/{collection_id}/file/add", json=payload, headers=headers
    )
    if not resp.ok:
        print(
            f"Failed to add file {file_id} to collection {collection_id}: {resp.text}"
        )


def main():
    if not os.path.exists(VAULT_MAP_FILE):
        print(f"Vault map file not found: {VAULT_MAP_FILE}")
        return

    with open(VAULT_MAP_FILE, "r", encoding="utf-8") as f:
        vault_data = json.load(f)

    sync_state = {}
    if os.path.exists(SYNC_STATE_FILE):
        with open(SYNC_STATE_FILE, "r", encoding="utf-8") as f:
            sync_state = json.load(f)

    collection_id = get_or_create_knowledge()
    if not collection_id:
        print("Cannot proceed without a target Knowledge Collection.")
        return

    processed = 0
    errors = 0
    skipped = 0

    print("Starting sync...")
    for file_path, file_info in vault_data.items():
        mtime = file_info.get("mtime", 0)
        data = file_info.get("data", {})
        gist = data.get("gist", "")

        if not gist:
            continue

        # Skip raw memory files to avoid double-ingestion
        if file_path.startswith(EVELYN_DIR) or file_path == PHYSICAL_DESC_FILE:
            skipped += 1
            continue

        # Check if already synced and unmodified
        if file_path in sync_state and sync_state[file_path] >= mtime:
            skipped += 1
            continue

        print(f"Uploading gist for: {file_path}")
        title = data.get("title", None)
        tags = data.get("tags", [])
        links = data.get("links", [])

        file_id = upload_gist_file(file_path, gist, tags, links, title=title)
        if file_id:
            add_file_to_knowledge(collection_id, file_id)
            sync_state[file_path] = mtime
            processed += 1

            # Save state every 50 files so we don't lose progress if interrupted
            if processed % 50 == 0:
                with open(SYNC_STATE_FILE, "w", encoding="utf-8") as f:
                    json.dump(sync_state, f, indent=4)
        else:
            errors += 1

        # Small delay to avoid hammering the API
        time.sleep(0.1)

    # Save final state
    with open(SYNC_STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(sync_state, f, indent=4)

    print(
        f"Sync complete. Processed: {processed}, Skipped: {skipped}, Errors: {errors}"
    )


if __name__ == "__main__":
    main()
