# vault_indexer.py
# date created: 2026-05-24 17:50:08
# date modified: 2026-08-28 12:27:45
# tags: #vault, #indexer, #mapping, #scans, #metadata

"""
vault_indexer.py -- Incrementally builds the Obsidian Vault index for Evelyn.

Walks the entire Obsidian Vault (OBSIDIAN_ROOT) and produces metadata and LLM-generated
gists, storing them in the fast evelyn_vault.db SQLite database.

Key design decisions:
  - Incremental: Only files with a changed mtime are re-processed, keeping
    runs fast even on large vaults. State is persisted in SQLite.
  - LLM gists: Each file's gist is generated by the model configured in
    evelyn_config.py via the local Ollama API. Falls back to a text slice on failure.
"""

import os
import re
import sys

# Anchoring paths before importing evelyn_config
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
for _d in (ROOT_DIR, TOOLS_DIR):
    if _d not in sys.path:
        sys.path.insert(0, _d)

import vault_db

import evelyn_config as cfg
from Evelyn.tools.frontmatter_utils import parse_frontmatter
from Evelyn.tools.path_utils import is_vault_excluded, normalize_vault_path
from Evelyn.tools.string_utils import clean_llm_gist

OBSIDIAN_ROOT = getattr(cfg, "VAULT_BASE_DIR", r"/home/rathius/obsidian_vault")

SUMMARY_MAX_CHARS = 500


def clean_gist(text: str) -> str:
    """Strip thinking tags, LaTeX markup, and leading 'summary:' prefixes from LLM output."""
    return clean_llm_gist(text)


def normalize_path(path: str) -> str:
    """Return a normalized lower-case path string for safe comparison."""
    return normalize_vault_path(path)


def is_excluded(dir_path: str) -> bool:
    """Determine if a directory path is in the exclusion list."""
    return is_vault_excluded(dir_path)


def extract_metadata(file_path, timeout=300):
    """Read a markdown file and extract metadata fields plus an LLM-generated summary.

    Args:
        file_path: Absolute path to the markdown document.
        timeout:   Timeout in seconds for the Ollama API request.

    Returns:
        Dict of metadata fields, or None if the file could not be read.
    """
    try:
        with open(file_path, encoding="utf-8", errors="ignore") as f:
            content = f.read()
    except OSError as e:
        print(f"Error reading {file_path}: {e}")
        return None

    # 1. Frontmatter extraction via canonical parser
    meta, _body = parse_frontmatter(content)

    raw_tags = meta.get("tags", [])
    if isinstance(raw_tags, str):
        fm_tags = [t.strip().strip("'\"#") for t in raw_tags.split(",") if t.strip().strip("'\"#")]
    elif isinstance(raw_tags, (list, set, tuple)):
        fm_tags = [str(t).strip().strip("'\"#") for t in raw_tags if str(t).strip().strip("'\"#")]
    else:
        fm_tags = []

    raw_aliases = meta.get("aliases", [])
    if isinstance(raw_aliases, str):
        fm_aliases = [a.strip().strip("'\"") for a in raw_aliases.split(",") if a.strip().strip("'\"")]
    elif isinstance(raw_aliases, (list, set, tuple)):
        fm_aliases = [str(a).strip().strip("'\"") for a in raw_aliases if str(a).strip().strip("'\"")]
    else:
        fm_aliases = []

    fm_rag_priority = str(meta.get("rag_priority", "normal")).strip().lower()
    fm_rag_pinned = bool(meta.get("rag_pinned", False))
    if isinstance(meta.get("rag_pinned"), str):
        fm_rag_pinned = meta.get("rag_pinned", "").strip().lower() in ("true", "yes", "1")

    # 2. H1 Extraction
    h1_match = re.search(r"^#\s+(.*)", content, re.MULTILINE)
    title = (
        h1_match.group(1).strip()
        if h1_match
        else os.path.splitext(os.path.basename(file_path))[0]
    )

    # 3. Inline Tags #tag
    inline_tags = re.findall(r"(?:^|\s)#([a-zA-Z0-9_/-]+)(?=\s|$)", content)
    all_tags = sorted(set(fm_tags + inline_tags))

    # 5. Gist / Summary (Sanitized)
    text_body = re.sub(r"^---\n(.*?)\n---", "", content, flags=re.DOTALL)
    text_body = re.sub(r"(?m)^#{1,6}\s+.*$", "", text_body)
    text_body = re.sub(r"(\*\*|__)(.*?)\1", r"\2", text_body)
    text_body = re.sub(r"(\*)(.*?)\1", r"\2", text_body)
    text_body = re.sub(r"!\[\[.*?\]\]", "", text_body)
    text_body = re.sub(r"!\[.*?\]\(.*?\)", "", text_body)
    text_body = re.sub(r"(?m)^>\s*\[!.*?\].*$", "", text_body)
    text_body = re.sub(r"(?m)^>.*$", "", text_body)
    text_body = re.sub(r"<[^>]+>", "", text_body)
    text_body = re.sub(
        r"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+",
        "",
        text_body,
    )
    text_body = re.sub(r"(?m)^[-*+]\s+(.*?):\s+", r"\1: ", text_body)
    text_body = re.sub(r"(?m)^[-*+]\s+", "", text_body)

    def replace_link(match):
        """Regex helper to extract link text from Obsidian wikilinks (supports piping)."""
        c = match.group(1)
        if "|" in c: return c.split("|")[1]
        return c

    text_body = re.sub(r"\[\[(.*?)\]\]", replace_link, text_body)
    text_body = re.sub(r"\s+", " ", text_body).strip()

    # Fast text preview snippet without blocking Ollama LLM calls
    summary = text_body[:SUMMARY_MAX_CHARS]
    if len(text_body) > SUMMARY_MAX_CHARS:
        summary += "..."

    return {
        "title":        title,
        "tags":         all_tags,
        "gist":         summary,
        "aliases":      fm_aliases,
        "rag_priority": fm_rag_priority,
        "rag_pinned":   fm_rag_pinned,
    }


def scan_vault():
    """Scan the Obsidian root folder incrementally, updating the SQLite database.

    Compares mtimes to skip unchanged files and deletes records of missing files.
    """
    vault_db.init_db()
    current_files = set()
    processed = 0

    print("Scanning vault...")
    for root, dirs, files in os.walk(OBSIDIAN_ROOT):
        dirs[:] = [d for d in dirs if not is_excluded(os.path.join(root, d))]
        for file in files:
            if not file.endswith(".md"): continue

            full_path = os.path.join(root, file)
            rel_path = os.path.relpath(full_path, OBSIDIAN_ROOT)
            current_files.add(rel_path)

            try:
                mtime = os.path.getmtime(full_path)
            except OSError:
                continue

            existing = vault_db.get_document(rel_path)
            if existing:
                mtime_unchanged = existing["mtime"] == mtime
                if mtime_unchanged:
                    continue

            metadata = extract_metadata(full_path)
            if metadata:
                new_mtime = os.path.getmtime(full_path)
                vault_db.upsert_document(
                    path=rel_path,
                    title=metadata["title"],
                    mtime=new_mtime,
                    gist=metadata["gist"],
                    rag_priority=metadata["rag_priority"],
                    rag_pinned=metadata["rag_pinned"],
                    tags=",".join(metadata["tags"]),
                    aliases=",".join(metadata["aliases"])
                )
                processed += 1
                if processed % 100 == 0:
                    print(f"  [CHECKPOINT] Processed {processed} files")

    existing_docs = vault_db.get_all_documents()
    for doc in existing_docs:
        if doc["path"] not in current_files:
            print(f"Removed: {doc['path']}")
            vault_db.delete_document(doc["path"])

    print(f"Scan complete: {processed} files processed")


def main():
    """Execute the fast local vault scan pipeline."""
    scan_vault()
    print("[VAULT MAP] Vault metadata indexed successfully.")


if __name__ == "__main__":
    main()
