# vault_indexer.py
# date created: 2026-05-24 17:50:08
# date modified: 2026-05-24 17:50:08
# tags: vault, indexer, mapping, scans, metadata

"""
vault_indexer.py -- Incrementally builds the Obsidian Vault index for Evelyn.

Walks the entire Obsidian Vault (OBSIDIAN_ROOT) and produces metadata and LLM-generated
gists, storing them in the fast evelyn_vault.db SQLite database.

Key design decisions:
  - Incremental: Only files with a changed mtime are re-processed, keeping
    runs fast even on large vaults. State is persisted in SQLite.
  - LLM gists: Each file's gist is generated by the model configured in
    evelyn_config.py via the local Ollama API. Falls back to a text slice on failure.
"""

import os
import re
import sys
import requests

# Anchoring paths
ROOT_DIR = r"C:\Projects\LocalAI"
TOOLS_DIR = r"C:\Projects\LocalAI\Evelyn\tools"
for _d in (ROOT_DIR, TOOLS_DIR):
    if _d not in sys.path:
        sys.path.insert(0, _d)

import evelyn_config as cfg
import vault_db

OBSIDIAN_ROOT = r"G:\My Drive\Obsidian_Vault"

EXCLUDE_DIRS = {
    "evelyn/archived",
    "evelyn/evelyn's context/context entries/extracted",
    "evelyn/evelyn's context/context entries/pending",
    "evelyn/pending_approvals",
    ".obsidian",
    "attachments",
    "bases",
    "templates",
}

SUMMARY_MAX_CHARS = 500

def clean_gist(text: str) -> str:
    text = re.sub(r"^.*?</think>", "", text, flags=re.DOTALL)
    text = re.sub(r"<think>.*", "", text, flags=re.DOTALL)
    text = re.sub(r"\\boxed\{.*?\}", "", text, flags=re.DOTALL)
    text = re.sub(r"(?im)^\*?\*?summary:?\*?\*?\s*", "", text)
    text = re.sub(r"\n{2,}", "\n", text)
    return text.strip()

def normalize_path(path):
    return os.path.normpath(path).lower()

def is_excluded(dir_path):
    rel_path = os.path.relpath(dir_path, OBSIDIAN_ROOT)
    norm_rel = normalize_path(rel_path)
    for exclude in EXCLUDE_DIRS:
        norm_exclude = normalize_path(exclude)
        if norm_rel == norm_exclude or norm_rel.startswith(norm_exclude + os.sep):
            return True
    parts = norm_rel.split(os.sep)
    for part in parts:
        if part.startswith("."): 
            return True
    return False

def extract_metadata(file_path, timeout=300):
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
        return None

    # 1. Frontmatter extraction
    frontmatter_match = re.search(r"^---\n(.*?)\n---", content, re.DOTALL)
    fm_tags = []
    fm_aliases = []
    fm_rag_priority = "normal"
    fm_rag_pinned = False
    
    if frontmatter_match:
        fm_text = frontmatter_match.group(1)
        tags_line = re.search(r"^tags:\s*(\[.*?\]|.*)$", fm_text, re.MULTILINE)
        if tags_line:
            raw_tags = tags_line.group(1)
            cleaned = raw_tags.replace("[", "").replace("]", "").replace('"', "").replace("'", "")
            fm_tags = [t.strip() for t in cleaned.split(",") if t.strip()]

        aliases_line = re.search(r"^aliases:\s*(\[.*?\]|.*)$", fm_text, re.MULTILINE)
        if aliases_line:
            raw_aliases = aliases_line.group(1)
            cleaned_a = raw_aliases.replace("[", "").replace("]", "").replace('"', "").replace("'", "")
            fm_aliases = [a.strip() for a in cleaned_a.split(",") if a.strip()]

        priority_line = re.search(r"^rag_priority:\s*(\S+)", fm_text, re.MULTILINE)
        if priority_line:
            fm_rag_priority = priority_line.group(1).strip().lower()

        pinned_line = re.search(r"^rag_pinned:\s*(\S+)", fm_text, re.MULTILINE)
        if pinned_line:
            fm_rag_pinned = pinned_line.group(1).strip().lower() == "true"

    # 2. H1 Extraction
    h1_match = re.search(r"^#\s+(.*)", content, re.MULTILINE)
    title = (
        h1_match.group(1).strip()
        if h1_match
        else os.path.splitext(os.path.basename(file_path))[0]
    )

    # 3. Inline Tags #tag
    inline_tags = re.findall(r"(?:^|\s)#([a-zA-Z0-9_/-]+)(?=\s|$)", content)
    all_tags = sorted(list(set(fm_tags + inline_tags)))

    # 5. Gist / Summary (Sanitized)
    text_body = re.sub(r"^---\n(.*?)\n---", "", content, flags=re.DOTALL)
    text_body = re.sub(r"(?m)^#{1,6}\s+.*$", "", text_body)
    text_body = re.sub(r"(\*\*|__)(.*?)\1", r"\2", text_body)
    text_body = re.sub(r"(\*)(.*?)\1", r"\2", text_body)
    text_body = re.sub(r"!\[\[.*?\]\]", "", text_body)
    text_body = re.sub(r"!\[.*?\]\(.*?\)", "", text_body)
    text_body = re.sub(r"(?m)^>\s*\[!.*?\].*$", "", text_body)
    text_body = re.sub(r"(?m)^>.*$", "", text_body)
    text_body = re.sub(r"<[^>]+>", "", text_body)
    text_body = re.sub(
        r"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+",
        "",
        text_body,
    )
    text_body = re.sub(r"(?m)^[-*+]\s+(.*?):\s+", r"\1: ", text_body)
    text_body = re.sub(r"(?m)^[-*+]\s+", "", text_body)

    def replace_link(match):
        c = match.group(1)
        if "|" in c: return c.split("|")[1]
        return c

    text_body = re.sub(r"\[\[(.*?)\]\]", replace_link, text_body)
    text_body = re.sub(r"\s+", " ", text_body).strip()

    summary = ""
    gist_failed = False
    if text_body:
        ollama_url = f"{cfg.OLLAMA_URL}/api/generate"
        prompt = (
            f"Summarize this document in 2-3 concise sentences. State facts directly "
            f"(e.g., 'Ricky discussed...' not 'The narrator describes...'). "
            f"Focus on: who is involved, what happened or was discussed, and the emotional tone. "
            f"No preamble, no meta-commentary.\n"
            f"After the summary, add a single line starting with 'Keywords:' listing 5-8 "
            f"conversational search terms someone might use to find this content "
            f"(e.g., casual synonyms, related topics, emotional states).\n\n"
            f"Title: {title}\n"
            f"Tags: {', '.join(all_tags)}\n"
            f"Content: {text_body}"
        )

        options = {"num_ctx": cfg.NUM_CTX}
        for key, val in {
            "temperature": 0.3,
            "min_p": cfg.MIN_P,
            "top_k": cfg.TOP_K,
            "top_p": cfg.TOP_P,
            "repeat_penalty": cfg.REPEAT_PENALTY,
            "repeat_last_n": cfg.REPEAT_LAST_N,
            "seed": cfg.SEED,
            "num_predict": 200,
        }.items():
            if val is not None:
                options[key] = val
        if cfg.STOP_SEQUENCES:
            options["stop"] = cfg.STOP_SEQUENCES

        try:
            payload = {
                "model": cfg.MODEL_NAME,
                "prompt": prompt,
                "stream": False,
                "think": False,
                "options": options,
            }
            ollama_response = requests.post(ollama_url, json=payload, timeout=timeout)
            if ollama_response.ok:
                summary = clean_gist(ollama_response.json().get("response", "").strip())
            else:
                print(f"  -> Ollama API error for {file_path}: {ollama_response.status_code}")
        except Exception as e:
            print(f"  -> Ollama API request failed for {file_path}: {e}")

    if not summary:
        gist_failed = True
        summary = text_body[:SUMMARY_MAX_CHARS]
        if len(text_body) > SUMMARY_MAX_CHARS:
            summary += "..."
        print(f"  -> [GIST FAILED] Using text-slice fallback for: {os.path.basename(file_path)}")

    return {
        "title":        title,
        "tags":         all_tags,
        "gist":         summary,
        "gist_failed":  gist_failed,
        "aliases":      fm_aliases,
        "rag_priority": fm_rag_priority,
        "rag_pinned":   fm_rag_pinned,
    }

def scan_vault():
    vault_db.init_db()
    current_files = set()
    processed = 0

    print("Scanning vault...")
    for root, dirs, files in os.walk(OBSIDIAN_ROOT):
        dirs[:] = [d for d in dirs if not is_excluded(os.path.join(root, d))]
        for file in files:
            if not file.endswith(".md"): continue
            
            full_path = os.path.join(root, file)
            rel_path = os.path.relpath(full_path, OBSIDIAN_ROOT)
            current_files.add(rel_path)

            try:
                mtime = os.path.getmtime(full_path)
            except OSError:
                continue

            existing = vault_db.get_document(rel_path)
            if existing:
                mtime_unchanged = existing["mtime"] == mtime
                if mtime_unchanged and not existing["gist_failed"]:
                    continue

            print(f"Processing: {rel_path}")
            metadata = extract_metadata(full_path)
            if metadata:
                new_mtime = os.path.getmtime(full_path)
                vault_db.upsert_document(
                    path=rel_path,
                    title=metadata["title"],
                    mtime=new_mtime,
                    gist=metadata["gist"],
                    gist_failed=metadata["gist_failed"],
                    rag_priority=metadata["rag_priority"],
                    rag_pinned=metadata["rag_pinned"],
                    tags=",".join(metadata["tags"]),
                    aliases=",".join(metadata["aliases"])
                )
                processed += 1
                if processed % 50 == 0:
                    print(f"  [CHECKPOINT] Processed {processed} files")

    existing_docs = vault_db.get_all_documents()
    for doc in existing_docs:
        if doc["path"] not in current_files:
            print(f"Removed: {doc['path']}")
            vault_db.delete_document(doc["path"])

    print(f"Scan complete: {processed} files processed")

def retry_failed_gists():
    RETRY_TIMEOUTS = [450, 600, 900]
    
    failed_docs = vault_db.get_failed_gists()
    failed_paths = [(doc["path"], os.path.join(OBSIDIAN_ROOT, doc["path"])) 
                    for doc in failed_docs 
                    if os.path.exists(os.path.join(OBSIDIAN_ROOT, doc["path"]))]

    if not failed_paths:
        return 0

    print(f"\n[RETRY] {len(failed_paths)} file(s) need gist retries.")

    still_failed = list(failed_paths)
    for attempt, timeout in enumerate(RETRY_TIMEOUTS, start=1):
        if not still_failed: break
        print(f"[RETRY] Round {attempt}/{len(RETRY_TIMEOUTS)} — timeout={timeout}s — {len(still_failed)} remaining")
        next_failed = []
        for rel_path, full_path in still_failed:
            print(f"  Retrying: {rel_path}")
            metadata = extract_metadata(full_path, timeout=timeout)
            if metadata and not metadata.get("gist_failed"):
                new_mtime = os.path.getmtime(full_path)
                vault_db.upsert_document(
                    path=rel_path,
                    title=metadata["title"],
                    mtime=new_mtime,
                    gist=metadata["gist"],
                    gist_failed=metadata["gist_failed"],
                    rag_priority=metadata["rag_priority"],
                    rag_pinned=metadata["rag_pinned"],
                    tags=",".join(metadata["tags"]),
                    aliases=",".join(metadata["aliases"])
                )
                print(f"  -> [OK] Gist generated at timeout={timeout}s")
            else:
                next_failed.append((rel_path, full_path))
        still_failed = next_failed

    return len(still_failed)

def main():
    scan_vault()
    still_failing = retry_failed_gists()
    
    if still_failing:
        print(f"\n[GIST SUMMARY] {still_failing} file(s) still using text-slice fallback after all retries.")
    else:
        print("\n[GIST SUMMARY] All gists generated successfully.")

if __name__ == "__main__":
    main()
