"""\r
generate_vault_map.py -- Incrementally builds the Obsidian Vault index for Evelyn.\r
\r
Walks the entire Obsidian Vault (``ROOT_DIR``) and produces:\r
\r
  vault_map_data.json      -- Machine-readable JSON index used by:\r
                               * ``ingest_gists.py`` to upload gist summaries\r
                                 to the Chroma ``evelyn_gists`` collection.\r
                               * ``context_manager.py`` for vault search\r
                                 (``search_vault_map()``).\r
\r
Key design decisions:\r
  - Incremental: Only files with a changed ``mtime`` are re-processed, keeping\r
    runs fast even on large vaults. State is persisted in ``vault_map_data.json``.\r
  - LLM gists: Each file's gist is generated by the model configured in\r
    ``evelyn_config.py`` (MODEL_NAME) via the local Ollama API.\r
    Falls back to a 500-character text slice on failure.\r
  - Vocabulary bridge: Gists include a Keywords line with conversational\r
    search terms to improve RAG retrieval accuracy.\r
  - Exclusions: Configured via ``EXCLUDE_DIRS`` (attachments, templates, archived\r
    entries, hidden folders).\r
\r
Run directly: ``python generate_vault_map.py``\r
"""

import os
import re
import json
import sys
import datetime
import requests

# Add project root so we can import evelyn_config
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import evelyn_config as cfg

# --- Configuration ---
ROOT_DIR = r"g:\My Drive\Obsidian_Vault"
OUTPUT_DIR = r"c:\Projects\LocalAI\Vault_Map"
STATE_FILE = os.path.join(OUTPUT_DIR, "vault_map_data.json")
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "Obsidian_Vault_Map.md")

# Paths/Folders to Exclude (normalized to lowercase for case-insensitive check)
EXCLUDE_DIRS = {
    "evelyn/archived",
    "evelyn/pending_approvals",
    ".obsidian",
    "attachments",
    "bases",
    "templates",
}

# --- Heuristics ---
SUMMARY_MAX_CHARS = 500


def clean_gist(text: str) -> str:
    """
    Strips LLM thinking artifacts from a gist string.

    Magistral (and similar reasoning models) sometimes leak their internal
    chain-of-thought into the response when ``think`` is not disabled.  The
    resulting gist may contain:

    * ``</think>`` tags (or trailing ``<think>`` openers without a closer)
    * A ``**Summary:**`` or ``Summary:`` preamble line
    * A ``\\boxed{...}`` block (LaTeX-style answer box)
    * Blank lines and stray punctuation left by the above

    This function removes all of the above and returns the cleanest
    single-paragraph summary it can find.

    Args:
        text: Raw gist string from the LLM (or loaded from cache).

    Returns:
        str: Cleaned gist, or the original string if nothing needed fixing.
    """
    import re as _re

    # 1. Strip everything up to and including the last </think> tag
    text = _re.sub(r"^.*?</think>", "", text, flags=_re.DOTALL)

    # 2. Strip orphaned opening <think> tags (no matching close)
    text = _re.sub(r"<think>.*", "", text, flags=_re.DOTALL)

    # 3. Strip \boxed{...} blocks (single or multi-line, with optional \text{} inside)
    text = _re.sub(r"\\boxed\{.*?\}", "", text, flags=_re.DOTALL)

    # 4. Strip **Summary:** / Summary: preamble lines
    text = _re.sub(r"(?im)^\*?\*?summary:?\*?\*?\s*", "", text)

    # 5. Collapse excess whitespace / blank lines
    text = _re.sub(r"\n{2,}", "\n", text)
    text = text.strip()

    return text


def normalize_path(path):
    """
    Normalises a file path to lower-case with OS-appropriate separators.

    Used internally for case-insensitive exclusion checks.

    Args:
        path: Any path string (absolute or relative).

    Returns:
        str: Normalised, lower-cased path.
    """
    return os.path.normpath(path).lower()


def is_excluded(dir_path):
    """
    Checks if the directory path (relative to root or absolute) is in the ignore list.
    """
    rel_path = os.path.relpath(dir_path, ROOT_DIR)
    norm_rel = normalize_path(rel_path)

    # Check absolute matches and sub-directories
    for exclude in EXCLUDE_DIRS:
        norm_exclude = normalize_path(exclude)
        if norm_rel == norm_exclude or norm_rel.startswith(norm_exclude + os.sep):
            return True

    # Check for excluded hidden folders like .obsidian/plugins (covered by startswith .obsidian)
    parts = norm_rel.split(os.sep)
    for part in parts:
        if part.startswith("."):  # Generic hidden folder ignore
            return True

    return False


def extract_metadata(file_path, timeout=300):
    """
    Extracts structured metadata and a natural-language gist from a markdown file.

    Extraction steps:
      1. **Frontmatter tags**: Parses the YAML ``tags:`` field (inline list or
         bare list format). Uses a regex heuristic; not a full YAML parser.
      2. **H1 title**: First ``# Heading`` in the file, or the filename stem
         as a fallback.
      3. **Inline tags**: All ``#tag`` patterns in the body (excludes headings).
      4. **LLM gist**: The cleaned body text is sent to the local Ollama API
         (model and options from ``evelyn_config.py``) with a summarisation prompt
         that also generates a Keywords vocabulary bridge line.
         A 500-character text slice is used as a fallback if Ollama is
         unavailable or returns an error. When the fallback is used,
         ``gist_failed`` is set to ``True`` in the returned dict so the entry
         is retried on every subsequent run.

    Args:
        file_path: Absolute path to the markdown file to process.
        timeout:   Seconds to wait for the Ollama API call (default 300).

    Returns:
        dict | None: Dictionary with keys ``title``, ``tags`` (sorted list),
        ``gist`` (str), and ``gist_failed`` (bool).
        Returns ``None`` if the file cannot be read.
    """
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
        return None

    # 1. Frontmatter extraction
    frontmatter_match = re.search(r"^---\n(.*?)\n---", content, re.DOTALL)
    fm_tags = []
    fm_aliases = []
    fm_rag_priority = "normal"
    fm_rag_pinned = False
    if frontmatter_match:
        fm_text = frontmatter_match.group(1)
        # Simple parsing for tags: [tag1, tag2] or list format
        # This is a basic heuristic, a full YAML parser could be used if needed but might be overkill
        # looking for keys "tags:"
        tags_line = re.search(r"^tags:\s*(\[.*?\]|.*)$", fm_text, re.MULTILINE)
        if tags_line:
            raw_tags = tags_line.group(1)
            # Remove brackets and split
            cleaned = (
                raw_tags.replace("[", "")
                .replace("]", "")
                .replace('"', "")
                .replace("'", "")
            )
            fm_tags = [t.strip() for t in cleaned.split(",") if t.strip()]

        # Parse aliases: [alias1, alias2]
        aliases_line = re.search(r"^aliases:\s*(\[.*?\]|.*)$", fm_text, re.MULTILINE)
        if aliases_line:
            raw_aliases = aliases_line.group(1)
            cleaned_a = (
                raw_aliases.replace("[", "")
                .replace("]", "")
                .replace('"', "")
                .replace("'", "")
            )
            fm_aliases = [a.strip() for a in cleaned_a.split(",") if a.strip()]

        # Parse rag_priority: high | normal | low
        priority_line = re.search(r"^rag_priority:\s*(\S+)", fm_text, re.MULTILINE)
        if priority_line:
            fm_rag_priority = priority_line.group(1).strip().lower()

        # Parse rag_pinned: true | false
        pinned_line = re.search(r"^rag_pinned:\s*(\S+)", fm_text, re.MULTILINE)
        if pinned_line:
            fm_rag_pinned = pinned_line.group(1).strip().lower() == "true"

    # 2. H1 Extraction
    h1_match = re.search(r"^#\s+(.*)", content, re.MULTILINE)
    title = (
        h1_match.group(1).strip()
        if h1_match
        else os.path.splitext(os.path.basename(file_path))[0]
    )

    # 3. Inline Tags #tag
    # Fix for variable width lookbehind error.
    # capturing the tag content, ensuring it's preceded by start or space.
    # We use (?:^|\s) to match start/space, but this consumes the character.
    # To catch multiple tags e.g. "#tag1 #tag2", simple findall with \s might overlap if sharing spaces?
    # Actually, standard practice for simple tag finding:
    inline_tags = re.findall(r"(?:^|\s)#([a-zA-Z0-9_/-]+)(?=\s|$)", content)

    all_tags = sorted(list(set(fm_tags + inline_tags)))

    # Wiki-link extraction and entity write-back removed (2026-04-26).
    # Obsidian tracks forward/back links natively. The new Keywords line
    # in the gist prompt provides the same search signal for RAG.

    # 5. Gist / Summary (Sanitized)
    # Remove frontmatter
    text_body = re.sub(r"^---\n(.*?)\n---", "", content, flags=re.DOTALL)

    # Remove Markdown Headers (lines starting with #)
    text_body = re.sub(r"(?m)^#{1,6}\s+.*$", "", text_body)

    # Remove bold/italic (**text**, *text*, __text__)
    text_body = re.sub(r"(\*\*|__)(.*?)\1", r"\2", text_body)
    text_body = re.sub(r"(\*)(.*?)\1", r"\2", text_body)

    # Remove Image embeds
    text_body = re.sub(r"!\[\[.*?\]\]", "", text_body)
    text_body = re.sub(r"!\[.*?\]\(.*?\)", "", text_body)

    # Remove Callouts and Spoilers
    text_body = re.sub(r"(?m)^>\s*\[!.*?\].*$", "", text_body)
    text_body = re.sub(r"(?m)^>.*$", "", text_body)

    # Remove HTML tags
    text_body = re.sub(r"<[^>]+>", "", text_body)

    # Remove URLs
    text_body = re.sub(
        r"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+",
        "",
        text_body,
    )

    # Clean Lists
    text_body = re.sub(r"(?m)^[-*+]\s+(.*?):\s+", r"\1: ", text_body)
    text_body = re.sub(r"(?m)^[-*+]\s+", "", text_body)

    # Remove Wiki-Link brackets (keep text)
    # [[Target]] -> Target, [[Target|Alias]] -> Alias
    def replace_link(match):
        content = match.group(1)
        if "|" in content:
            return content.split("|")[1]
        return content

    text_body = re.sub(r"\[\[(.*?)\]\]", replace_link, text_body)

    # Normalize Whitespace
    text_body = re.sub(r"\s+", " ", text_body).strip()

    # Generate Summary via local Ollama LLM
    summary = ""
    gist_failed = False
    if text_body:
        ollama_url = f"{cfg.OLLAMA_URL}/api/generate"
        prompt = (
            f"Summarize this document in 2-3 concise sentences. State facts directly "
            f"(e.g., 'Ricky discussed...' not 'The narrator describes...'). "
            f"Focus on: who is involved, what happened or was discussed, and the emotional tone. "
            f"No preamble, no meta-commentary.\n"
            f"After the summary, add a single line starting with 'Keywords:' listing 5-8 "
            f"conversational search terms someone might use to find this content "
            f"(e.g., casual synonyms, related topics, emotional states).\n\n"
            f"Title: {title}\n"
            f"Tags: {', '.join(all_tags)}\n"
            f"Content: {text_body}"
        )

        # Build options to match the main chat config — prevents Ollama
        # from evicting the loaded model to reload with different params.
        options = {"num_ctx": cfg.NUM_CTX}
        for key, val in {
            "temperature": 0.3,  # Lower temp for deterministic summaries
            "min_p": cfg.MIN_P,
            "top_k": cfg.TOP_K,
            "top_p": cfg.TOP_P,
            "repeat_penalty": cfg.REPEAT_PENALTY,
            "repeat_last_n": cfg.REPEAT_LAST_N,
            "seed": cfg.SEED,
            "num_predict": 200,  # 2-3 sentences + keywords = ~150 tokens max
        }.items():
            if val is not None:
                options[key] = val
        if cfg.STOP_SEQUENCES:
            options["stop"] = cfg.STOP_SEQUENCES

        try:
            payload = {
                "model": cfg.MODEL_NAME,
                "prompt": prompt,
                "stream": False,
                "think": False,  # Simple summarization — no reasoning chain needed
                "options": options,
            }
            ollama_response = requests.post(ollama_url, json=payload, timeout=timeout)
            if ollama_response.ok:
                summary = clean_gist(ollama_response.json().get("response", "").strip())
            else:
                print(
                    f"  -> Ollama API error for {file_path}: {ollama_response.status_code}"
                )
        except Exception as e:
            print(f"  -> Ollama API request failed for {file_path}: {e}")

    # Fallback text slice if LLM failed or body was empty.
    # Mark gist_failed=True so the entry is retried on every subsequent run
    # until a real LLM summary is produced. "Bad data in, bad data out."
    if not summary:
        gist_failed = True
        summary = text_body[:SUMMARY_MAX_CHARS]
        if len(text_body) > SUMMARY_MAX_CHARS:
            summary += "..."
        print(f"  -> [GIST FAILED] Using text-slice fallback for: {os.path.basename(file_path)}")

    return {
        "title":        title,
        "tags":         all_tags,
        "gist":         summary,
        "gist_failed":  gist_failed,
        "aliases":      fm_aliases,
        "rag_priority": fm_rag_priority,
        "rag_pinned":   fm_rag_pinned,
    }


def scan_vault(state):
    """
    Walks the vault, skips unchanged files, processes new/changed ones.
    Re-processes entries with gist_failed=True regardless of mtime.
    Updates 'state' dictionary in place.
    """
    current_files = set()
    processed = 0

    print("Scanning vault...")
    for root, dirs, files in os.walk(ROOT_DIR):
        # Filter directories in place
        dirs[:] = [d for d in dirs if not is_excluded(os.path.join(root, d))]

        for file in files:
            if not file.endswith(".md"):
                continue

            full_path = os.path.join(root, file)
            rel_path = os.path.relpath(full_path, ROOT_DIR)
            current_files.add(rel_path)

            try:
                mtime = os.path.getmtime(full_path)
            except OSError:
                continue

            # Incremental check — re-process if mtime changed OR last gist failed
            existing = state.get(rel_path)
            if existing:
                mtime_unchanged = existing["mtime"] == mtime
                prev_failed = existing.get("data", {}).get("gist_failed", False)
                if mtime_unchanged and not prev_failed:
                    continue  # Unchanged and gist is good — skip

            # Process File
            print(f"Processing: {rel_path}")
            metadata = extract_metadata(full_path)
            if metadata:
                # Re-fetch mtime because extract_metadata may have modified the file
                new_mtime = os.path.getmtime(full_path)
                state[rel_path] = {"mtime": new_mtime, "data": metadata}
                processed += 1

                # Periodic checkpoint — saves progress every 50 files
                if processed % 50 == 0:
                    with open(STATE_FILE, "w", encoding="utf-8") as f:
                        json.dump(state, f, indent=2)
                    print(f"  [CHECKPOINT] Saved after {processed} files")

    # Cleanup deleted files
    keys_to_remove = [k for k in state.keys() if k not in current_files]
    for k in keys_to_remove:
        print(f"Removed: {k}")
        del state[k]

    print(f"Scan complete: {processed} files processed")
    return state


# generate_markdown() removed (2026-04-26).
# The human-readable Obsidian_Vault_Map.md atlas is no longer generated.
# Obsidian tracks tags, links, and entities natively.
# The machine-readable vault_map_data.json remains for search_vault_map().



def generate_json_output(state):
    """
    Generates a clean JSON string of the vault data for AI parsing.
    Removes system metadata like 'mtime' to save tokens/space.
    """
    clean_data = []
    for rel_path, entry in state.items():
        data = entry["data"]
        # Add path to the data object for context
        item = {"path": rel_path}
        item.update(data)
        clean_data.append(item)

    # Sort for consistent diffs
    clean_data.sort(key=lambda x: x["path"])

    final_output = {
        "metadata": {
            "generated_at": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "description": "High-level index of the Obsidian Vault.",
            "file_count": len(clean_data),
        },
        "files": clean_data,
    }

    return json.dumps(final_output, indent=2)


# generate_last_week_journal() removed (2026-04-26).
# Evelyn's tools can dynamically query journal entries as needed.



def retry_failed_gists(state):
    """
    Phase 2: retry any entries still marked gist_failed=True with escalating timeouts.

    Attempt order: 450s → 600s → 900s.
    Saves state after each success so progress survives an early exit.
    Returns the number of entries still failed after all retry rounds.
    """
    RETRY_TIMEOUTS = [450, 600, 900]

    failed_paths = [
        (rel_path, os.path.join(ROOT_DIR, rel_path))
        for rel_path, entry in state.items()
        if entry.get("data", {}).get("gist_failed", False)
        and os.path.exists(os.path.join(ROOT_DIR, rel_path))
    ]

    if not failed_paths:
        return 0

    print(f"\n[RETRY] {len(failed_paths)} file(s) need gist retries.")

    still_failed = list(failed_paths)
    for attempt, timeout in enumerate(RETRY_TIMEOUTS, start=1):
        if not still_failed:
            break
        print(f"[RETRY] Round {attempt}/{len(RETRY_TIMEOUTS)} — timeout={timeout}s — {len(still_failed)} remaining")
        next_failed = []
        for rel_path, full_path in still_failed:
            print(f"  Retrying: {rel_path}")
            metadata = extract_metadata(full_path, timeout=timeout)
            if metadata and not metadata.get("gist_failed"):
                new_mtime = os.path.getmtime(full_path)
                state[rel_path]["mtime"] = new_mtime
                state[rel_path]["data"] = metadata
                print(f"  -> [OK] Gist generated at timeout={timeout}s")
                # Checkpoint after each success
                with open(STATE_FILE, "w", encoding="utf-8") as f:
                    json.dump(state, f, indent=2)
            else:
                next_failed.append((rel_path, full_path))
        still_failed = next_failed

    return len(still_failed)


def main():
    """
    Entry point: runs the full incremental vault map generation pipeline.

    Execution order:
      1. Load the existing state from ``vault_map_data.json``.
      2. Retroactively clean any thinking-mode artifacts from cached gists.
      3. Phase 1 — ``scan_vault()``: walk the vault, re-process changed files
         and any entries with ``gist_failed=True``, GC deleted entries.
      4. Save state.
      5. Phase 2 — ``retry_failed_gists()``: retry remaining failures with
         escalating timeouts (450s → 600s → 900s). Saves after each success.
      6. Generate ``Obsidian_Vault_Map.md`` and ``The_Last_Week.md``.
      7. Print a summary showing how many gists still need attention.
    """
    # Load State
    if os.path.exists(STATE_FILE):
        try:
            with open(STATE_FILE, "r", encoding="utf-8") as f:
                state = json.load(f)
        except Exception:
            state = {}
    else:
        state = {}

    # One-time retroactive gist cleanup (fixes artifacts from thinking-mode runs)
    cleaned_count = 0
    for rel_path, entry in state.items():
        if "data" in entry and "gist" in entry["data"]:
            original = entry["data"]["gist"]
            cleaned = clean_gist(original)
            if cleaned != original:
                entry["data"]["gist"] = cleaned
                cleaned_count += 1
    if cleaned_count:
        print(f"Cleaned {cleaned_count} cached gists with thinking artifacts.")

    # Phase 1: Normal incremental scan
    state = scan_vault(state)

    # Save state after Phase 1
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)

    # Phase 2: Retry failed gists with escalating timeouts
    still_failing = retry_failed_gists(state)

    # Final save (captures any retry successes not already checkpointed)
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)

    # Generate JSON output (machine-readable index for search_vault_map)
    generate_json_output(state)
    print(f"Vault map data saved to: {STATE_FILE}")



    # End-of-run failure summary
    total_failed = sum(
        1 for entry in state.values()
        if entry.get("data", {}).get("gist_failed", False)
    )
    if total_failed:
        print(f"\n[GIST SUMMARY] {total_failed} file(s) still using text-slice fallback after all retries.")
        print("  These will be retried automatically on the next vault map generation.")
        print("  To inspect: search for '\"gist_failed\": true' in vault_map_data.json")
    else:
        print("\n[GIST SUMMARY] All gists generated successfully.")


if __name__ == "__main__":
    main()
